### ISSUE TITLE
When zooming, camera appears to be off

### ISSUE THREAD

**Issue by mjtorn** [godotengine/escoria#111] opened 2018-04-08 18:27 UTC
To reproduce this, zoom in on a location in a scene. The camera will be off, though nothing in the coordinates or anything will appear to be off.

My theory is that the scaling is done from `(0, 0)` by sort of stretching the visible area in front of the camera, which is why the camera is off without really being off.

Does anyone know of a phenomenon like this or is my theory entirely off? Anything to fix it?

**Comment by fleskesvor** [comment] 2018-04-08 19:38
> To reproduce this, zoom in on a location in a scene.

I'm not sure what you mean by this. Neither of the zoom functions take a positional parameter, I think. The camera has its origin in the upper right corner, so unless your esc script also calls `camera_set_pos` you will just zoom closer and closer to the upper left corner of the original viewport. 

I agree that this behaviour isn't great though, and that maybe ideally you'd want to be able to call it with a global_id which could be used to anchor the position of the zoom.

**Comment by fleskesvor** [comment] 2018-04-25 21:58
@mjtorn Can you confirm that #130 gives the desired behavior?

**Comment by fleskesvor** [comment] 2018-04-28 20:57
> There's something that looks weird to my eye (or brain) but I think it's me expecting this to be centered without having a camera position where the characters are in the middle.

The characters in the above screenshots are not in the middle. Maybe that's the issue?

> There's also the question of the blurry background. My image is 1350px high, so I thought the camera would use the background image's pixels as they are available instead of scaling the visible ones.

Make sure both filter and mipmaps is unchecked in the import dock, then press reimport if you had to change either.

**Comment by mjtorn** [comment] 2018-04-29 09:43
> The characters in the above screenshots are not in the middle. Maybe that's the issue?

Yeah, like I said, it's the brain thinking they should be centered but they aren't. This happens despite the camera following the player (I think that's how the camera works now), so there probably is that drift thing when the camera doesn't need to move.

Problem is that `camera_set_target 0 helga` or `camera_set_target 0 helga player` doesn't center them either, so is there still the possibility of a bug in the position code?

I think a command for centering an object and/or coordinates with or without a speed, as best as possible considering the screen limits, would help here either way.

> Make sure both filter and mipmaps is unchecked in the import dock, then press reimport if you had to change either.

Ooh, thanks! There is some pixelation, but I believe that's natural, because I don't have an insane amount to work with. This should probably be documented in #45 at least or somewhere :)

**Comment by fleskesvor** [comment] 2018-04-29 21:53
> Problem is that `camera_set_target 0 helga` or `camera_set_target 0 helga` player doesn't center them either, so is there still the possibility of a bug in the position code?
>
> I think a command for centering an object and/or coordinates with or without a speed, as best as possible considering the screen limits, would help here either way.

That is what `camera_set_target` should do, so if that's not working, that's definitely a bug. Was it working for you at some point until recently? If so, I can perform a bisect and figure out when it broke (probably in #130).

**Comment by mjtorn** [comment] 2018-04-30 11:55
I delved a bit into 9aec17fa95af5363b849c7ada848b15c8f08906e

The changes in `game.gd` are fine.

The camera clamping code has to be in, for some reason, to make the camera move between `player` and `helga`.

If it's in, the zoom mechanism has to be altered from `camera.zoom` back to scaling the scene, which is obviously not ok. So we must find a way to get rid of the clamping code to use the proper zoom.

If I print like `printt("move camera from ", cpos, " to pos ", pos)` in `update_camera()`, it always says it moves the camera.

With the clamping code, it ends up printing nonstop

> move camera from 	(960, 810)	 to pos 	(179.169006, 1301.630005)

Without the clamping code, ie. the camera _does NOT visibly move_, it ends with (and does not keep on printing because there's no code to clamp it)

> move camera from 	(185.031921, 1299.446411)	 to pos 	(179.169006, 1301.630005)

These coordinates look so different that could it be a similar problem to the `get_global_mouse_position()` thing?

**Comment by fleskesvor** [comment] 2018-04-30 21:12
I'm not able to reproduce this issue. I've created a branch with your esc script from #130 and `Sprite` and `TextureRect` backgrounds (demo rooms "room2" and "room3"), in case the difference mattered, but the camera seems to be behaving as expected in both rooms:

https://github.com/fleskesvor/escoria/tree/fix-camera-move

Are you able to create a minimal example with this issue present?

**Comment by mjtorn** [comment] 2018-05-01 15:05
@fleskesvor I tried this by removing the parallaxing in room 2 and the failures are the same.

You want to drag Helga way off to the right and the player a bit to the left.

Bug 1: The camera doesn't go all the way to your Helga, though the player can walk over there

Then drag the player to the lower-left corner, where it would be clamped, I suppose.

Bug 2: The camera does not move to Helga at all, despite `printt()` debugging saying it would.

The Bug 2 scenario is literally what I have, the player starts off in the lower-left corner.

**Comment by mjtorn** [comment] 2018-05-01 17:02
As commented on IRC, taking room2 from that branch and setting a greater distance between player and helga causes bugs _because_ setting camera targets isn't a blocking operation.

The fact the camera gets stuck if the player's at the edge is actually about the distance between the player and helga and how that affects the non-blocking move, not the player's distance to the edge as I first thought.

**Comment by mjtorn** [comment] 2018-05-01 17:39
And in my prototype, where the camera move takes pretty sharply 1.5 seconds, now I have to add another 1.5 seconds to it. This isn't an exact science, I haven't calculated the times precisely, but things work surprisingly well by doubling the time.

**Comment by fleskesvor** [comment] 2018-05-01 19:28
> setting camera targets isn't a blocking operation

I opened #144 about this issue.

So I think the issue that is still relevant to this discussion is that it should be possible to set zoom to target a specific object in the room and also take an optional time, so that it doesn't just snap into position at the current center of the viewport.

Is that accurate, @mjtorn?

A workaround for now is to use `camera_zoom_in` in combination with `camera_set_target`, but the result won't look very smooth.

**Comment by mjtorn** [comment] 2018-05-02 14:51
That description is akkurat yes. But I don't really see how to achieve it with `camera_zoom_in` calls except having a million of them in an esc script...

**Comment by fleskesvor** [comment] 2018-05-02 22:05
> That description is akkurat yes. But I don't really see how to achieve it with `camera_zoom_in` calls except having a million of them in an esc script...

Yeah, having a million of them is what I was thinking of. Not a good solution, I agree. 🙁

**Comment by mjtorn** [comment] 2018-05-06 15:09
I did some investigation to support the PR above (though it should be merged as-is)

My NPC is at (1411, 842) and `camera_set_target` does not center on her. If I use `camera_set_pos 0 1600 600` I get much more pleasing results than even with `camera_set_pos 0 1411 842` or `camera_set_target`.

Could this still be some kind of a coordinate/projection type thing?

Be that as it may, in a pinch, we can work with iterating coordinates for `camera_set_pos` and the zooming.

**Comment by fleskesvor** [comment] 2018-05-06 18:36
As mentioned in #148, I think what happens is that `camera_set_target`/`camera_set_pos` finishes moving before the `camera_set_zoom`/`camera_set_zoom_height` and that the new center of the camera is left of the NPC because of the camera limits, so that by the time the camera is done zooming, it will have zoomed the NPC to the edge of the camera.

This can be tested by setting the camera limits on the instanced `game` scene in the room you're testing on (make the `w` parameter a very large value) to enable the camera to move outside of your background `Sprite`.

It should also be possible to iterate over the vectors passed to `camera_set_target` up front to calculate accumulative distance and make a version of it that takes seconds as a parameter instead of speed, which should make it easier to get the timing right.

**Comment by dploeger** [comment] 2021-07-09 20:44
After a rewrite from scratch, Escoria will be re-released in the coming weeks. Because of this, we're closing this issue, because it relates to the old code. If the issue also regards the rewritten code, please feel free to reopen it.

Thanks

**Closed by dploeger** 2021-07-09 20:44 UTC
Labels: enhancement
