### ISSUE TITLE
Change main player during game

### ISSUE THREAD

**Issue by ricpelo** [godotengine/escoria#14] opened 2017-04-14 09:52 UTC
Is there a way to change the main player during the game, as seen on Maniac Mansion, Thimbleweed Park and so? I can't find anything about that in the docs.

https://fr.flossmanuals.net/creating-point-and-click-games-with-escoria/main-player/

**Comment by StraToN** [comment] 2017-04-15 10:14
Indeed, this would be a nice feature to add to Escoria.

**Comment by ricpelo** [comment] 2017-04-15 12:24
Great! ;)

**Comment by punto-** [comment] 2017-04-16 05:18
I agree. The main issue with this feature is that we don't really have a
"global state" where characters have a position in the global world (which
includes which screen they're in, etc). I don't know if this is necessary
tho, since we could just require all playable characters to be instanced in
all scenes (like we do right now). Then we can have a "set_current_player"
command, which designates the player (ie the character that receives input
from the user, etc). The other character that is not the "current_player"
needs to respond to standard .esc commands, like set active or set_state,
etc. That might also be an issue since we use a different script for the
player and items, but those 2 scripts duplicate a lot of functionality (in
fact they could be the same script). I don't think player has a "state",
that'll be the main missing feature from player.gd. Lastly, I think there
might be a couple of places where the code recognizes that the global id of
an item is "player" and does something special with it, that's just a
matter of finding them and replacing for a check on the "current_player".

**Comment by fleskesvor** [comment] 2017-05-28 22:20
I've experimented a bit with multiple players this weekend, and it's really not difficult to achieve rudimentary support for this, as demonstrated by my example implementation:

https://github.com/fleskesvor/escoria/tree/feat/multiple_players

The main thing is to replace all references to the player by node name to instead use a group for players and have a boolean determine which player is currently active. This works well, and by giving each player their own global_id, it's easy to add an esc command to change players, used like eg. "set_player player2".

There are a few things that need a bit of consideration for this to work properly though:

* As mentioned by @punto- above, players need to respond to esc commands, eg. for states and animations, and being able to interact with the other player, like when you want to ask them to take over.
* Should players have shared or separate inventories, or should that be easy to change with a setting? For instance, it would be easy to switch inventories when players are switched by saving player specific inventories under a global_id prefixed global, like eg. "player2inv/ice_cream", but I don't think there's an easy way to do it from an esc script.
* Should a flag be updated, indicating which player is the current player, so it can be used to give different commands depending on player in esc scripts, or should that be up to the developer? Probably the latter, but it seems needlessly verbose to (almost) always have to accompany a "set_player" command with something like "set_global player2_current true/false".

**Comment by punto-** [comment] 2017-05-29 03:52
For the esc commands I think the best is to unify the player and
item/interactive scripts, there's no reason to have those separate.. the
player is just an item with fancy walk animations (items already have a bit
of that too), and responds to user input.

For separate inventories, I think that's entirely up to the inventory UI
script. As you mention we current use "i/item_name", so we could have an
interface that also responds to i2/item_name, and that's the 2nd
inventory.. I think the node hierarchy inside the inventory already
reflects that, all the items are children of a "i" node. That was the
intention of moving the inventory to just be globals. Maybe we need a
mechanism to signal the inventory ui that it needs to switch to a different
inventory, that's not necessarily tied to the current player tho

It's a good idea to have a flag with the current player, maybe something
like p/player_name = true, and set the current one to false, that could be
done automatically by the set_player command.. That way we don't
necessarily need to know all the players in advance (and the user can just
clear all the "p/" globals if they want to)

**Comment by fleskesvor** [comment] 2017-05-29 15:27
I did some conservative refactoring of those scripts, and I've made player.gd and item_background.gd extend item.gd, which I think is what you suggested, @punto-? This seems to work well, as it's now easy to attach esc scripts to players nodes, to have them "pass control" via dialogue.

Upon doing so, I realized another thing that need some thought; namely what to do about the "interactivity" of the current player. By default, you can interact with yourself, which while possibly useful at times, this might not be the expected behavior. So, maybe changing player should also make the current player ignore mouse input?

The other thoughts on inventories and current player flags by @punto- seem like good ideas to me.

**Comment by punto-** [comment] 2017-05-29 16:13
I'd say either make player inherit item.gd, or move most of the item code
to interactive.gd and make player and item inherit that (I'm opening a
separate issue for the item and item_background confusion). I'm not sure
what code would be specific to items that doesn't go on players too..

**Comment by fleskesvor** [comment] 2017-05-29 21:20
I did put my refactoring from earlier into a [separate branch](https://github.com/fleskesvor/escoria/tree/unify_interactive_scripts), so I could submit a pull request for just that, leaving the current issue aside for now. However, while the difference between item.gd and item_background.gd is trivial (there's actually #16 for that, so no need to open another issue), there's too much complexity in interactive.gd and player.gd that I can confidently say that my branch is a good solution, so it's probably best that someone more familiar with the code handles that.

Things _seem_ to work for me after merging the changes into my multiple player branch, adding Control and Position2D nodes to the player scene and esc scripts for interaction, but that's rarely a good measure without extensive testing.

**Comment by dploeger** [comment] 2021-07-09 20:45
After a rewrite from scratch, Escoria will be re-released in the coming weeks. Because of this, we're closing this issue, because it relates to the old code. If the issue also regards the rewritten code, please feel free to reopen it.

Thanks

**Closed by dploeger** 2021-07-09 20:45 UTC
Labels: enhancement
