### ISSUE TITLE
Rpg elements in Escoria

### ISSUE THREAD

**Issue by zero2000** [godotengine/escoria#26] opened 2017-07-21 21:21 UTC
Hi, I open this topic because I have seen that Escoria has potential but it would be useful to implement things that I have seen in the genre of visual novels (the Persona saga and Stein Gates) that are very interesting as what is the management of time . As in the attached image you will see that in the upper left not only the date, but also plays an important point, as well as the phone that reacts according to the date. 

![28341822-e37fb580-6bda-11e7-9384-a15901d4e9d7](https://user-images.githubusercontent.com/3870686/28482975-910a9100-6e30-11e7-8f79-c92c054d1a93.jpg)

I hope you can play or watch on youtube the videos of gamer about these game and other points and click to capture the best ideas I have implanted in Escoria

**Comment by fleskesvor** [comment] 2017-12-06 20:46
I've looked a bit at some gameplay videos of Steins Gate and Persona, and I think I know what you mean with time management now.

Persona seems to be similar to 3D point-and-clicks like Grim Fandango and Escape from Monkey Island in terms of interaction, as you move close to an item to interact with it. I don't think Escoria supports anything like that currently, but it seems like a good idea to think about supporting gamepads.

There's also the passing of time, which seems to be triggered by going to sleep. That can be done by loading a new scene when the player interacts with the bed, or use the same scene but change states to hide/show items/NPCs and/or set a global to change logic in .esc scripts.

Steins Gate seems to be similar in terms of time. It also has that time/calendar display, which doubles as a marker for things happening on the phone. This effect can be triggered by setting state on an item to play an animation. The phone would also need extensive use of animations to support different things happening on screen.

There also seems to be some sort of interaction going on with the phone. I'm not sure how this works, but if it has small interactive areas in varying positions, you might have to implement that by placing several small items with attached esc scripts for logic on top of the phone, which you can also toggle the visibility of and/or animate.

Another idea, which might not work for a Steins Gate-esque game, is to place a custom dialogue on top of the phone, made to match the screen visually. The dialogue system of Escoria is very flexible, but it's unfortunately a bit tricky to figure out.

Let me know if there are things I missed or misunderstood.

**Comment by zero2000** [comment] 2017-12-15 14:08
Exactly, but that should be thought of as scum, since Godot has overwhelming potential. and I see how the games of the persona saga or Steins Gate are visual novels, but they are very interactive in the saga. The person is half visual novel and half a fight game with pokemon things. instead if it is raised a gui could be created so that also those who start in this world can do it with drag and drop and when they have confidence they can mess with the scripts. think about it to attract users escoria

**Comment by fleskesvor** [comment] 2018-01-11 13:24
Ok, that's good to hear, since it sounds like it should be possible to create the sort of games you want with the current features of Escoria, except movement and interaction with a gamepad. If you think that's essential, I think that should be created in a new issue as a feature request.

A GUI to create games with the framework is also on the roadmap, and should be covered by #5, though the issue isn't very fleshed out, so feel free to suggest features you think should be supported there.

In addition to Adventure Creator for Unity, there's also AGS and Visionaire, which are very popular for adventure games. AGS is extremely popular with indie developers because it's free and has a big community, but engine development is more or less abandoned. There's also XAGE, which is a more modern engine, inspired by AGS and developed by one person.

**Comment by zero2000** [comment] 2018-01-19 23:38
Yes, that's what I thought and as I read that they plan to rewrite the framework, I should consider implementing that, to make it easier for the beginners, as well as the function of code editing for those who wish to create their own scripts, as well as seen that native This script should be used as a way to write the .esc files because they could make them more modular, ie say. create in core and with the native script to generate the pieces, of course those pieces must be created from the same frame so that there are no problems, as well as integrate the animation and sound system that look very good. and you should see persona 5 analyze their mechanics, in that direction should evolve escoria, has a very good visual novel system away from combat. that is to say. godot use escoria in some parts and escoria use godot in others, I think I let myself understand, if not write me to clarify certain things.

![persona 5](https://cdn4.dualshockers.com/wp-content/uploads/2017/04/Persona5-56.jpg)

**Comment by dploeger** [comment] 2021-07-09 20:45
After a rewrite from scratch, Escoria will be re-released in the coming weeks. Because of this, we're closing this issue, because it relates to the old code. If the issue also regards the rewritten code, please feel free to reopen it.

Thanks

**Closed by dploeger** 2021-07-09 20:45 UTC
Labels: enhancement
