### ISSUE TITLE
Animation not found: release_input

### ISSUE THREAD

**Issue by jdknox** [godotengine/escoria#116] opened 2018-04-12 21:59 UTC
I am running the latest Escoria pull (unmodified clone, actually) from `master` on Godot 3.0.2 official.  I get an error that the `release_input` animation is not found in the `telon` scene.  When I check the `animation` node on that scene I also cannot find such an animation.  Did this animation exist previously?

<img width="1011" alt="screen shot 2018-04-12 at 14 52 36" src="https://user-images.githubusercontent.com/926182/38706294-805a8444-3e61-11e8-9999-88f33696c594.png">

```
0:00:01:0130 - Animation not found: release_input
----------
Type:Error
Description: Animation not found: release_input
Time: 0:00:01:0130
C Error: Method/Function Failed.
C Source: scene/animation/animation_player.cpp:888
C Function: play
```

https://github.com/godotengine/escoria/blob/9a068043ab88485c7daa3f223bed66813b618452/device/globals/telon.gd#L123

**Comment by fleskesvor** [comment] 2018-04-15 23:36
Thanks for the bug report. The `telon.gd` script seems to have been largely unchanged since the initial commit of the 2.1 version a year and a half ago. It's possible that an animation from the animation player was changed during that time, but since the telon scene used a binary format before and I don't have the Godot 2.1 installed on this computer, I'll have to do some digging to figure it out. Perhaps @StraToN knows a bit more about this? I also noticed that there's a return statement in `set_input_catch()`, which makes half of that function redundant.

**Comment by mjtorn** [comment] 2018-04-16 13:10
I haven't seen this problem. Were there any exotic circumstances when this popped up?

**Comment by fleskesvor** [comment] 2018-04-20 07:48
I've looked into it a bit, and I think I understand what its purpose was and why it's not needed anymore. My theory is that mouse input filtering is a feature that didn't exist when this was first made, so they might have used a technique that is frequently used in web development to create modal message boxes; to create a semi-transparent overlay with z-index between the actual page and the message box. I couldn't find any trace of this in the code since it was first released on GitHub, and since the telon now uses a mouse filter to block input while fading, I don't think it's needed.

I will take a proper look at it this weekend, remove anything that isn't used and make sure it's working as intended.

**Comment by jdknox** [comment] 2018-04-24 01:53
Thanks for looking into this.  It really helps my understanding of how Escoria functions under the hood.

In my testing I just removed the part looking for that animation and it worked fine, but I haven't tested dialog yet.

**Comment by jdknox** [comment] 2018-04-24 01:55
@mjtorn This came up from an unmodified clone straight from github.

**Comment by mjtorn** [comment] 2018-04-24 05:46
On Tue, Apr 24, 2018 at 01:55:51AM +0000, Jeff wrote:
>@mjtorn This came up from an unmodified clone straight from github.

Yeah, ok, when looking closer, it's one of those errors I learned to
ignore because I haven't been negatively affected by it :D

These should be fixed instead of picking up bad habits of ignoring
errors...

**Comment by StraToN** [comment] 2021-07-05 16:44
Not relevant anymore in Escoria 4.

**Closed by StraToN** 2021-07-05 16:44 UTC
